apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: tamboot-cloud-admin-frontend
    tier: frontend
  name: tamboot-cloud-admin-frontend
  namespace: frontend
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: tamboot-cloud-admin-frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: tamboot-cloud-admin-frontend
    spec:
      containers:
        - image: >-
            registry-vpc.cn-shenzhen.aliyuncs.com/registry_tam/tamboot-cloud-admin-frontend:1.0.0-SNAPSHOT
          imagePullPolicy: Always
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /usr/share/nginx/html/tamboot-cloud-admin
              name: volume-html-src
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - emptyDir: {}
          name: volume-html-src